### PR TITLE
software availability on multiple platform

### PR DESCRIPTION
**Pull request by shdwkl**
Change hard-coded path to UI files which result an error message on Linux or Mac to more aware method using pathlib

[`pathlib`](https://docs.python.org/3/library/pathlib.html) builtin to python.

### CODE REVIEW

**Review by 0xGhazy — COMMENTED** [review]
@yusufadell 
do you test these changes? , I was working on it using os.path.join method.

and if you want to contribute please open an issue and ask me to assign it to you. to help each other and work together.

**Comment by 0xGhazy** [comment]
do you test these changes?

**Comment by shdwkl** [comment]
> and if you want to contribute please open an issue and ask me to assign it to you. to help each other and work together.

i'd love to collaborate but i can't make such a commitment to contribute; cuz i have final exams in the upcoming weeks, Stay productive!

**Comment by 0xGhazy** [comment]
like me bro😥. I'm waiting for you anytime you wanna contribute ❤

**Pull request merged**
